"""add_locations_config

Revision ID: 24b5800c0457
Revises: 9497df1ea7a6
Create Date: 2026-03-06 01:11:02.188478

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '24b5800c0457'
down_revision: Union[str, None] = '9497df1ea7a6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('location_tolerance_overrides',
    sa.Column('location_id', sa.String(length=36), nullable=False),
    sa.Column('tolerance_pct', sa.Float(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('location_id')
    )
    op.create_table('locations',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('city', sa.String(length=100), nullable=False),
    sa.Column('address', sa.String(length=500), nullable=False),
    sa.Column('tolerance_pct_override', sa.Float(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('system_config',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('default_tolerance_pct', sa.Float(), nullable=False),
    sa.Column('approval_sla_hours', sa.Integer(), nullable=False),
    sa.Column('dow_lookback_weeks', sa.Integer(), nullable=False),
    sa.Column('daily_reminder_time', sa.String(length=5), nullable=False),
    sa.Column('data_retention_years', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('system_config')
    op.drop_table('locations')
    op.drop_table('location_tolerance_overrides')
    # ### end Alembic commands ###
