"""add_access_grants_location_fields

Revision ID: 537d31465f1c
Revises: a63f7872cf30
Create Date: 2026-03-06 01:54:57.736988

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '537d31465f1c'
down_revision: Union[str, None] = 'a63f7872cf30'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('access_grants',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('user_name', sa.String(length=200), nullable=False),
    sa.Column('user_email', sa.String(length=200), nullable=False),
    sa.Column('user_role', sa.String(length=30), nullable=False),
    sa.Column('access_type', sa.String(length=20), nullable=False),
    sa.Column('note', sa.Text(), nullable=False),
    sa.Column('granted_by', sa.String(length=36), nullable=False),
    sa.Column('granted_by_name', sa.String(length=200), nullable=False),
    sa.Column('granted_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_access_grants_user_id'), 'access_grants', ['user_id'], unique=False)
    op.add_column('locations', sa.Column('expected_cash', sa.Float(), nullable=False, server_default='0.0'))
    op.add_column('locations', sa.Column('sla_hours', sa.Integer(), nullable=False, server_default='24'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('locations', 'sla_hours')
    op.drop_column('locations', 'expected_cash')
    op.drop_index(op.f('ix_access_grants_user_id'), table_name='access_grants')
    op.drop_table('access_grants')
    # ### end Alembic commands ###
