"""add_verifications

Revision ID: 5583db8448a1
Revises: ef4ce69c54cf
Create Date: 2026-03-06 01:32:22.456241

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5583db8448a1'
down_revision: Union[str, None] = 'ef4ce69c54cf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('verifications',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('verification_type', sa.Enum('CONTROLLER', 'DGM', name='verificationtype'), nullable=False),
    sa.Column('location_id', sa.String(length=36), nullable=False),
    sa.Column('location_name', sa.String(length=200), nullable=False),
    sa.Column('verifier_id', sa.String(length=36), nullable=False),
    sa.Column('verifier_name', sa.String(length=200), nullable=False),
    sa.Column('verification_date', sa.String(length=10), nullable=False),
    sa.Column('scheduled_time', sa.String(length=5), nullable=True),
    sa.Column('day_of_week', sa.Integer(), nullable=False),
    sa.Column('day_name', sa.String(length=10), nullable=False),
    sa.Column('status', sa.Enum('SCHEDULED', 'COMPLETED', 'MISSED', 'CANCELLED', name='verificationstatus'), nullable=False),
    sa.Column('warning_flag', sa.Boolean(), nullable=False),
    sa.Column('warning_reason', sa.String(length=50), nullable=True),
    sa.Column('observed_total', sa.Float(), nullable=True),
    sa.Column('variance_vs_imprest', sa.Float(), nullable=True),
    sa.Column('variance_pct', sa.Float(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=False),
    sa.Column('missed_reason', sa.Text(), nullable=True),
    sa.Column('signature_data', sa.Text(), nullable=True),
    sa.Column('month_year', sa.String(length=7), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_verifications_location_id'), 'verifications', ['location_id'], unique=False)
    op.create_index(op.f('ix_verifications_status'), 'verifications', ['status'], unique=False)
    op.create_index(op.f('ix_verifications_verification_date'), 'verifications', ['verification_date'], unique=False)
    op.create_index(op.f('ix_verifications_verification_type'), 'verifications', ['verification_type'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_verifications_verification_type'), table_name='verifications')
    op.drop_index(op.f('ix_verifications_verification_date'), table_name='verifications')
    op.drop_index(op.f('ix_verifications_status'), table_name='verifications')
    op.drop_index(op.f('ix_verifications_location_id'), table_name='verifications')
    op.drop_table('verifications')
    # ### end Alembic commands ###
