"""add visit_section_reviews to verifications

Revision ID: 9f1e23117647
Revises: cb2fe8643f6b
Create Date: 2026-03-31 04:15:41.877647

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9f1e23117647'
down_revision: Union[str, None] = 'cb2fe8643f6b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('verifications', sa.Column('visit_section_reviews', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('verifications', 'visit_section_reviews')
    # ### end Alembic commands ###
