"""add_audit

Revision ID: a63f7872cf30
Revises: 5583db8448a1
Create Date: 2026-03-06 01:45:32.074288

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a63f7872cf30'
down_revision: Union[str, None] = '5583db8448a1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_events',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('event_type', sa.String(length=60), nullable=False),
    sa.Column('actor_id', sa.String(length=36), nullable=False),
    sa.Column('actor_name', sa.String(length=200), nullable=False),
    sa.Column('actor_role', sa.String(length=30), nullable=False),
    sa.Column('location_id', sa.String(length=36), nullable=True),
    sa.Column('location_name', sa.String(length=200), nullable=True),
    sa.Column('entity_id', sa.String(length=36), nullable=True),
    sa.Column('entity_type', sa.String(length=60), nullable=True),
    sa.Column('detail', sa.Text(), nullable=False),
    sa.Column('old_value', sa.Text(), nullable=True),
    sa.Column('new_value', sa.Text(), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_audit_created_at', 'audit_events', ['created_at'], unique=False)
    op.create_index(op.f('ix_audit_events_actor_id'), 'audit_events', ['actor_id'], unique=False)
    op.create_index(op.f('ix_audit_events_created_at'), 'audit_events', ['created_at'], unique=False)
    op.create_index(op.f('ix_audit_events_event_type'), 'audit_events', ['event_type'], unique=False)
    op.create_index(op.f('ix_audit_events_location_id'), 'audit_events', ['location_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_audit_events_location_id'), table_name='audit_events')
    op.drop_index(op.f('ix_audit_events_event_type'), table_name='audit_events')
    op.drop_index(op.f('ix_audit_events_created_at'), table_name='audit_events')
    op.drop_index(op.f('ix_audit_events_actor_id'), table_name='audit_events')
    op.drop_index('ix_audit_created_at', table_name='audit_events')
    op.drop_table('audit_events')
    # ### end Alembic commands ###
