"""add_reasonableness_reports_and_location_group

Revision ID: bda23550142c
Revises: 9f1e23117647
Create Date: 2026-04-02 02:34:41.086599

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bda23550142c'
down_revision: Union[str, None] = '9f1e23117647'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reasonableness_reports',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('group_key', sa.String(length=50), nullable=False),
    sa.Column('cost_center', sa.String(length=50), nullable=False),
    sa.Column('location_labels', sa.String(length=500), nullable=False),
    sa.Column('from_date', sa.Date(), nullable=False),
    sa.Column('to_date', sa.Date(), nullable=False),
    sa.Column('factor', sa.Float(), nullable=False),
    sa.Column('preparer', sa.String(length=200), nullable=False),
    sa.Column('scope', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('REASONABLE', 'OVERFUNDED', name='reasonablenessstatus'), nullable=False),
    sa.Column('location_reports', sa.JSON(), nullable=False),
    sa.Column('saved_by', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reasonableness_reports_group_key'), 'reasonableness_reports', ['group_key'], unique=False)
    op.create_index(op.f('ix_reasonableness_reports_saved_by'), 'reasonableness_reports', ['saved_by'], unique=False)
    op.create_index(op.f('ix_reasonableness_reports_status'), 'reasonableness_reports', ['status'], unique=False)
    op.add_column('locations', sa.Column('group', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('locations', 'group')
    op.drop_index(op.f('ix_reasonableness_reports_status'), table_name='reasonableness_reports')
    op.drop_index(op.f('ix_reasonableness_reports_saved_by'), table_name='reasonableness_reports')
    op.drop_index(op.f('ix_reasonableness_reports_group_key'), table_name='reasonableness_reports')
    op.drop_table('reasonableness_reports')
    # ### end Alembic commands ###
