"""add_cost_center_to_locations

Revision ID: c95e39ff8f6e
Revises: c2e8f3a1d904
Create Date: 2026-03-21 12:36:02.984802

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c95e39ff8f6e'
down_revision: Union[str, None] = 'c2e8f3a1d904'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('locations', sa.Column('cost_center', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('locations', 'cost_center')
    # ### end Alembic commands ###
