"""add section_reviews to submissions

Revision ID: cb2fe8643f6b
Revises: de0fc9b341f7
Create Date: 2026-03-30 22:58:56.935763

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cb2fe8643f6b'
down_revision: Union[str, None] = 'de0fc9b341f7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('submissions', sa.Column('section_reviews', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('submissions', 'section_reviews')
    # ### end Alembic commands ###
