"""add_submissions

Revision ID: ef4ce69c54cf
Revises: 24b5800c0457
Create Date: 2026-03-06 01:20:19.341575

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ef4ce69c54cf'
down_revision: Union[str, None] = '24b5800c0457'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('missed_submissions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('location_id', sa.String(length=36), nullable=False),
    sa.Column('missed_date', sa.String(length=10), nullable=False),
    sa.Column('reason', sa.String(length=100), nullable=False),
    sa.Column('detail', sa.Text(), nullable=False),
    sa.Column('supervisor_name', sa.String(length=200), nullable=False),
    sa.Column('logged_by', sa.String(length=36), nullable=False),
    sa.Column('logged_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_missed_submissions_location_id'), 'missed_submissions', ['location_id'], unique=False)
    op.create_table('submissions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('location_id', sa.String(length=36), nullable=False),
    sa.Column('location_name', sa.String(length=200), nullable=False),
    sa.Column('operator_id', sa.String(length=36), nullable=False),
    sa.Column('operator_name', sa.String(length=200), nullable=False),
    sa.Column('submission_date', sa.String(length=10), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'PENDING_APPROVAL', 'APPROVED', 'REJECTED', name='submissionstatus'), nullable=False),
    sa.Column('source', sa.Enum('FORM', 'CHAT', 'EXCEL', name='submissionsource'), nullable=False),
    sa.Column('sections', sa.JSON(), nullable=False),
    sa.Column('total_cash', sa.Float(), nullable=False),
    sa.Column('expected_cash', sa.Float(), nullable=False),
    sa.Column('variance', sa.Float(), nullable=False),
    sa.Column('variance_pct', sa.Float(), nullable=False),
    sa.Column('variance_exception', sa.Boolean(), nullable=False),
    sa.Column('variance_note', sa.Text(), nullable=True),
    sa.Column('approved_by', sa.String(length=36), nullable=True),
    sa.Column('approved_by_name', sa.String(length=200), nullable=True),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('rejection_reason', sa.Text(), nullable=True),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_submissions_location_id'), 'submissions', ['location_id'], unique=False)
    op.create_index(op.f('ix_submissions_operator_id'), 'submissions', ['operator_id'], unique=False)
    op.create_index(op.f('ix_submissions_status'), 'submissions', ['status'], unique=False)
    op.create_index(op.f('ix_submissions_submission_date'), 'submissions', ['submission_date'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_submissions_submission_date'), table_name='submissions')
    op.drop_index(op.f('ix_submissions_status'), table_name='submissions')
    op.drop_index(op.f('ix_submissions_operator_id'), table_name='submissions')
    op.drop_index(op.f('ix_submissions_location_id'), table_name='submissions')
    op.drop_table('submissions')
    op.drop_index(op.f('ix_missed_submissions_location_id'), table_name='missed_submissions')
    op.drop_table('missed_submissions')
    # ### end Alembic commands ###
